---
title: "SDA_WaterLoss_Rethinking"
output: html_document
date: "2025-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





#VH2O Stuff









```{r}

sd_tidy_VH2O <- SDAmaster %>%
  mutate(SpeciesTrialType = paste(Species, TrialType, sep = "_")) %>%
  filter(Individual %in% c("BthieM01", "BbrygM02")) %>%
  filter(TrialType %in% c("xp", "controlxp"))





#This makes a dataset with all of the variables + New standardized Variables
sd_tidyH2O  = sd_tidy_VH2O %>% 
  mutate(T2 = standardize(Time_Actual),
         STT = as.integer(as.factor(SpeciesTrialType)),
         H2O = standardize(Average_VH2O),
         Species1 = as.integer(as.factor(Species)),
         TrialType1 = as.integer(as.factor(TrialType)),
         CPercent = standardize(Cricket_Percent),
         logmass = log(Body_Mass),
         logmass1 = standardize(logmass),
         TrialType,
         Species)


sd_short_H2O = sd_tidyH2O %>% dplyr::select(H2O, Species1, Species, T2, TrialType1, CPercent, TrialType, STT, logmass1)

```






```{r}
H2O_Time_heros <-ulam(
alist(
  H2O ~ dnorm(mu,sigma),
  #This includes an interaction between Time and Time squared since it is likely an upside down parabola. Each time you add the bracketed things it adds another line for that category
  mu <- a1[STT] + b1[STT] * T2 + b2[STT] * T2^2 + b3[STT] * logmass1 + b4[STT] * CPercent,
  c(a1, b1, b2, b3, b4)[STT] ~ multi_normal(c(a, b), Rho, sigma_id),
  a ~ dnorm(0, 1),
  b ~ dnorm(0, 1),
  sigma_id ~ dexp(1),
  Rho ~ lkj_corr(2),
  sigma ~ dexp(1)
) ,data = sd_short_H2O, chains = 4, cores = 4)
```



```{r}
precis(H2O_Time_heros, depth = 3)
```


```{r}
# Set up a multi-panel layout: 2 rows, 3 columns (for 6 STT categories)
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1))

# X-axis sequence
t2_seq <- seq(-1.3, 2.6, length.out = 30)

stt_colors2 <- c("blue", "blue", "red", "red") 

# Define the real names for each STT category
stt_names <- c( "Brygooi H2O Fasted after xp", "Brygooi H2O xp", "Thieli H2O Fasted after xp", "Thieli H2O xp")


# Loop through each STT category
for (stt in 1:4) {
  # Generate posterior predictions
  mu_pred <- link(H2O_Time_heros, data = data.frame(T2 = t2_seq, STT = stt,
    logmass1 = mean(sd_short_H2O$logmass1[sd_short_H2O$STT == stt], na.rm = TRUE),
    CPercent = mean(sd_short_H2O$CPercent[sd_short_H2O$STT == stt], na.rm = TRUE)))
  
  # Calculate mean and 95% CI
  mu_mean <- apply(mu_pred, 2, mean)
  mu_PI <- apply(mu_pred, 2, PI, prob = 0.95)
  
  # Filter observed data for this STT category
  observed_data <- sd_short_H2O %>% filter(STT == stt)
  
  # Plot observed data
  plot(observed_data$T2, observed_data$H2O,
       col = "black", pch = 16, cex = 0.7,
       xlab = "Time", ylab = "VH2O",
       main = stt_names[stt],
       ylim = range(c(observed_data$H2O, mu_PI)),
       xlim = range(t2_seq))
  
  # Add predicted mean line
  lines(t2_seq, mu_mean, col = stt_colors2[stt], lwd = 2)
  
  # Add shaded confidence intervals
  polygon(c(t2_seq, rev(t2_seq)),
          c(mu_PI[1, ], rev(mu_PI[2, ])),
          col = rgb(0, 0, 1, alpha = 0.2), border = NA)
}

# Reset layout to single panel
par(mfrow = c(1, 1))
```

```{r}
#This creates the x axis of the plot
t4_seq = seq(-1.3, 2.6, length.out = 1000)


mu_pred1b <- link(H2O_Time_heros, data = data.frame(T2 = t4_seq,
                                       STT = 2,
    logmass1 = mean(sd_short_H2O$logmass1[sd_short_H2O$STT == stt], na.rm = TRUE),
    CPercent = mean(sd_short_H2O$CPercent[sd_short_H2O$STT == stt], na.rm = TRUE)))
mu_mean1b <- apply(mu_pred1b, 2, mean)
mu_PI1b <- apply(mu_pred1b, 2, PI, prob = 0.95)

times = tibble(t4_seq = t4_seq) %>% 
  mutate(name = paste0("V", row_number()))
mu_pred1b %>% as_data_frame() %>% 
  mutate(iter = 1:nrow(.)) %>% 
  pivot_longer(cols = -iter) %>% 
  left_join(times) %>% 
  group_by(iter) %>% 
  filter(value == max(value)) %>% 
  ungroup %>% 
  reframe(mean = mean(t4_seq),
          sd = sd(t4_seq))

tibble(mean = mu_mean1b,
       lower = mu_PI1b[1,],
       upper = mu_PI1b[2,],
       sd = sd(mu_mean1b),
       time = t4_seq) %>% 
  arrange(-mean)

mean_H2O_Brygooi <- 0.7531850995 * sd(sd_tidy_VH2O$Average_VH2O) + mean(sd_tidy_VH2O$Average_VH2O)
upper_H2O_Brygooi <- (0.7531850995 + 1.96 * (0.4919126)) * sd(sd_tidy_VH2O$Average_VH2O) + mean(sd_tidy_VH2O$Average_VH2O)
lower_H2O_Brygooi <- (0.7531850995 - 1.96 * (0.4919126)) * sd(sd_tidy_VH2O$Average_VH2O) + mean(sd_tidy_VH2O$Average_VH2O)


mean_H2O_Brygooi
upper_H2O_Brygooi
lower_H2O_Brygooi

mean_Htime_Brygooi <- -1.276458 * sd(sd_tidy_VH2O$Time_Actual) + mean(sd_tidy_VH2O$Time_Actual)
upper_Htime_Brygooi <- (-1.276458 + 1.96 * (0.301274)) * sd(sd_tidy_VH2O$Time_Actual) + mean(sd_tidy_VH2O$Time_Actual)
lower_Htime_Brygooi <- (-1.276458 - 1.96 * (0.301274)) * sd(sd_tidy_VH2O$Time_Actual) + mean(sd_tidy_VH2O$Time_Actual)


mean_Htime_Brygooi
upper_Htime_Brygooi
lower_Htime_Brygooi
```




```{r}
#This creates the x axis of the plot
t4_seq = seq(-1.3, 2.6, length.out = 1000)


mu_pred1b <- link(H2O_Time_heros, data = data.frame(T2 = t4_seq,
                                       STT = 4,
    logmass1 = mean(sd_short_H2O$logmass1[sd_short_H2O$STT == stt], na.rm = TRUE),
    CPercent = mean(sd_short_H2O$CPercent[sd_short_H2O$STT == stt], na.rm = TRUE)))
mu_mean1b <- apply(mu_pred1b, 2, mean)
mu_PI1b <- apply(mu_pred1b, 2, PI, prob = 0.95)

times = tibble(t4_seq = t4_seq) %>% 
  mutate(name = paste0("V", row_number()))
mu_pred1b %>% as_data_frame() %>% 
  mutate(iter = 1:nrow(.)) %>% 
  pivot_longer(cols = -iter) %>% 
  left_join(times) %>% 
  group_by(iter) %>% 
  filter(value == max(value)) %>% 
  ungroup %>% 
  reframe(mean = mean(t4_seq),
          sd = sd(t4_seq))

tibble(mean = mu_mean1b,
       lower = mu_PI1b[1,],
       upper = mu_PI1b[2,],
       sd = sd(mu_mean1b),
       time = t4_seq) %>% 
  arrange(-mean)

mean_H2O_Thieli <- 0.700836481 * sd(sd_tidy_VH2O$Average_VH2O) + mean(sd_tidy_VH2O$Average_VH2O)
upper_H2O_Thieli <- (0.700836481 + 1.96 * (0.5168837)) * sd(sd_tidy_VH2O$Average_VH2O) + mean(sd_tidy_VH2O$Average_VH2O)
lower_H2O_Thieli <- (0.700836481 - 1.96 * (0.5168837) * sd(sd_tidy_VH2O$Average_VH2O)) + mean(sd_tidy_VH2O$Average_VH2O)


mean_H2O_Thieli
upper_H2O_Thieli
lower_H2O_Thieli

mean_Htime_Thieli <- -0.005465465 * sd(sd_tidy_VH2O$Time_Actual) + mean(sd_tidy_VH2O$Time_Actual)
upper_Htime_Thieli <- (-0.005465465 + 1.96 * (0.08911943)) * sd(sd_tidy_VH2O$Time_Actual) + mean(sd_tidy_VH2O$Time_Actual)
lower_Htime_Thieli <- (-0.005465465 - 1.96 * (0.08911943)) * sd(sd_tidy_VH2O$Time_Actual) + mean(sd_tidy_VH2O$Time_Actual)


mean_Htime_Thieli
upper_Htime_Thieli
lower_Htime_Thieli
```




```{r}
#This creates the x axis of the plot
t4_seq = seq(-1.3, 2.6, length.out = 1000)


mu_pred1b <- link(H2O_Time_heros, data = data.frame(T2 = t4_seq,
                                       STT = 3,
    logmass1 = mean(sd_short_H2O$logmass1[sd_short_H2O$STT == stt], na.rm = TRUE),
    CPercent = mean(sd_short_H2O$CPercent[sd_short_H2O$STT == stt], na.rm = TRUE)))
mu_mean1b <- apply(mu_pred1b, 2, mean)
mu_PI1b <- apply(mu_pred1b, 2, PI, prob = 0.95)

times = tibble(t4_seq = t4_seq) %>% 
  mutate(name = paste0("V", row_number()))
mu_pred1b %>% as_data_frame() %>% 
  mutate(iter = 1:nrow(.)) %>% 
  pivot_longer(cols = -iter) %>% 
  left_join(times) %>% 
  group_by(iter) %>% 
  filter(value == max(value)) %>% 
  ungroup %>% 
  reframe(mean = mean(t4_seq),
          sd = sd(t4_seq))

tibble(mean = mu_mean1b,
       lower = mu_PI1b[1,],
       upper = mu_PI1b[2,],
       sd = sd(mu_mean1b),
       time = t4_seq) %>% 
  arrange(-mean)

mean_H2O_ThieliC <- -1.284143 * sd(sd_tidy_VH2O$Average_VH2O) + mean(sd_tidy_VH2O$Average_VH2O)
upper_H2O_ThieliC <- (-1.284143 + 1.96 * (0.363936)) * sd(sd_tidy_VH2O$Average_VH2O) + mean(sd_tidy_VH2O$Average_VH2O)
lower_H2O_ThieliC <- (-1.284143 - 1.96 * (0.363936) * sd(sd_tidy_VH2O$Average_VH2O)) + mean(sd_tidy_VH2O$Average_VH2O)


mean_H2O_ThieliC
upper_H2O_ThieliC
lower_H2O_ThieliC

mean_Htime_ThieliC <- 0.6245114 * sd(sd_tidy_VH2O$Time_Actual) + mean(sd_tidy_VH2O$Time_Actual)
upper_Htime_ThieliC <- (0.6245114 + 1.96 * (0.1878726)) * sd(sd_tidy_VH2O$Time_Actual) + mean(sd_tidy_VH2O$Time_Actual)
lower_Htime_ThieliC <- (0.6245114 - 1.96 * (0.1878726)) * sd(sd_tidy_VH2O$Time_Actual) + mean(sd_tidy_VH2O$Time_Actual)


mean_Htime_ThieliC
upper_Htime_ThieliC
lower_Htime_ThieliC
```













VH2O Over Time







```{r}
sd_tidy_VH2OE <- SDAmaster %>%
  mutate(TrialTypeTimeRange = paste(TrialType, TimeRange, sep = "_")) %>%
  filter(TimeRange %in% c("0-12", "13-24"))%>%
  filter(TrialType %in% c("xp", "7p"))






#This makes a dataset with all of the variables + New standardized Variables
sd_tidyH2OE  = sd_tidy_VH2OE %>% 
  mutate(T3 = standardize(Time),
         TTR = as.integer(as.factor(TrialTypeTimeRange)),
         H2O = standardize(Average_VH2O),
         Species1 = as.integer(as.factor(Species)),
         TrialType1 = as.integer(as.factor(TrialType)),
         CPercent = standardize(Cricket_Percent),
         logmass = log(Body_Mass),
         logmass1 = standardize(logmass),
         TrialType,
         Species)


sd_short_H2OE = sd_tidyH2OE %>% dplyr::select(H2O, Species1, Species, T3, TrialType1, CPercent, TrialType, TTR, logmass1)

```




```{r}
H2O_TimeE <-ulam(
alist(
  H2O ~ dnorm(mu,sigma),
  #This includes an interaction between Time and Time squared since it is likely an upside down parabola. Each time you add the bracketed things it adds another line for that category
  mu <- a1[TTR] + b1[TTR] * T3 + b3[TTR] * logmass1 + b4[TTR] * CPercent,
  c(a1, b1, b3, b4)[TTR] ~ multi_normal(c(a, b), Rho, sigma_id),
  a ~ dnorm(0, 1),
  b ~ dnorm(0, 1),
  sigma_id ~ dexp(1),
  Rho ~ lkj_corr(2),
  sigma ~ dexp(1)
) ,data = sd_short_H2OE, chains = 4, cores = 4)
```

```{r}
precis(H2O_TimeE, depth = 3)
```



```{r}
# Set up a multi-panel layout: 2 rows, 3 columns (for 6 STT categories)
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1))

# X-axis sequence
t2_seq <- seq(-1.3, 2.6, length.out = 30)

ttr_colors2 <- c("blue", "blue", "red", "red") 

# Define the real names for each STT category
ttr_names <- c( "7p 0-12", "7p 13-24", "xp 0-12", "xp 13-24")


# Loop through each STT category
for (ttr in 1:4) {
  # Generate posterior predictions
  mu_pred <- link(H2O_TimeE, data = data.frame(T3 = t2_seq, TTR = ttr,
    logmass1 = mean(sd_short_H2OE$logmass1[sd_short_H2OE$TTR == ttr], na.rm = TRUE),
    CPercent = mean(sd_short_H2OE$CPercent[sd_short_H2OE$TTR == ttr], na.rm = TRUE)))
  
  # Calculate mean and 95% CI
  mu_mean <- apply(mu_pred, 2, mean)
  mu_PI <- apply(mu_pred, 2, PI, prob = 0.95)
  
  # Filter observed data for this STT category
  observed_data <- sd_short_H2OE %>% filter(TTR == ttr)
  
  # Plot observed data
  plot(observed_data$T3, observed_data$H2O,
       col = "black", pch = 16, cex = 0.7,
       xlab = "Time", ylab = "VH2O",
       main = ttr_names[ttr],
       ylim = range(c(observed_data$H2O, mu_PI)),
       xlim = range(t2_seq))
  
  # Add predicted mean line
  lines(t2_seq, mu_mean, col = ttr_colors2[ttr], lwd = 2)
  
  # Add shaded confidence intervals
  polygon(c(t2_seq, rev(t2_seq)),
          c(mu_PI[1, ], rev(mu_PI[2, ])),
          col = rgb(0, 0, 1, alpha = 0.2), border = NA)
}

# Reset layout to single panel
par(mfrow = c(1, 1))
```





